### ISSUE TITLE
Upgrade to new Gsap Version

### ISSUE THREAD

**Issue by zenonn37** [RoyalMist/meteor-gsap#6]
Hi, I was wondering if you intend to upgrade the package to the new GSAP version.
Thanks Chris.

**Comment by RoyalMist** [comment]
Hello,

I will do it tomorrow. I received the newsletter yesterday. 

---

Cordialement,

Thibault Fouache

**Comment by zenonn37** [comment]
Thanks!

**Comment by RoyalMist** [comment]
This will be dome this evening sorry for the delay. 

---

Cordialement,

Thibault Fouache
